### ISSUE TITLE
PacketTunnel Crashes: EXC_RESOURCE -> exceeded mem limit: ActiveHard 50 MB

### ISSUE THREAD

**Issue by zharkikholeg** [wanliyunyan/xray_ios#19]
The problem is that iOS allows only 50MB memory limit for Packet Tunnel Provider (source: https://developer.apple.com/forums/thread/73148?answerId=693017022#693017022). After startTunnel() function is called the process takes up around 30 MB already, without any load, and putting some load makes it to cross the threshold and crash. 

**Example log from Console app:**
```
EXC_RESOURCE -> PacketTunnel[38382] exceeded mem limit: ActiveHard 50 MB (fatal)
memorystatus: killing process 38382 [PacketTunnel] in high band FOREGROUND (100) - memorystatus_available_pages: 173195
memorystatus: killing_specific_process pid 38382 [PacketTunnel] (per-process-limit 100) 51201KB - memorystatus_available_pages: 173203
Process PacketTunnel [38382] killed by jetsam reason per-process-limit
Extension com.example.vpn.PacketTunnel died unexpectedly
Formulating fatal 309 report for corpse[38382] PacketTunnel
```

**The fastest way to reproduce:** 
Start the tunnel, open [whoer.net](http://whoer.net/) in Safari, reload it several times. On 2nd-4th reload PacketTunnel crashes. 

**Device info:** 
Main device for testing: iPhone 15 Pro, iOS 17.2.1
Also tried on: iPhone 13 iOS 18.3, iPhone 11 iOS 16.3, iPhone 7 iOS 15.7. 
The issue is consistent between all these devices.  

**What I tried:**
The first thing I tried was limiting available memory and timeouts in Tun2SocksKit config. 
Default config:
```
       tunnel:
          mtu: 8500

        socks5:
          port: 10808
          address: ::1
          udp: 'udp'

        misc:
          # task stack size (bytes)
  	  task-stack-size: 24576 # 20480 + tcp-buffer-size
  	  # tcp buffer size (bytes)
  	  tcp-buffer-size: 4096
          connect-timeout: 5000
          read-write-timeout: 60000
          log-file: stderr
          log-level: error.
          limit-nofile: 65535
```

Config I modified in a way that would still work and pass Speedtest app test: 
```
       tunnel:
          mtu: 8500

        socks5:
          port: 10808
          address: ::1
          udp: 'udp'

        misc:
          # task stack size (bytes)
  	  task-stack-size: 12800 # 12800 is the min for Speedtest not to fail
  	  # tcp buffer size (bytes)
  	  tcp-buffer-size: 4096 # 4096 is the min for Speedtest not to fail
          connect-timeout: 2000 # 2000 ms is the min for Speedtest not to fail
          read-write-timeout: 10000 # 10000 ms is the min for Speedtest not to fail
          log-file: stderr
          log-level: error.
          limit-nofile: 65535
```

I could actually break the tunnel setting these values way too low, so I guess they work. If I go lower on these numbers - Speedtest’s upload speed test breaks and shows network error instead of completing. Also tried setting MTU lower, did not change anything.
The problem is, the new Tun2SocksKit config did not resolve the issue. So then I tried playing with LibXray’s maxMemory. My default was 50 MB, which is obviously too high. I guessed that setting it to 24 MB would fix the problem, but nothing actually changed. I also tried 16 MB, 8 MB and even 2MB, but nothing changed again - the Tunnel works fine for some time and then crashes. I also tried setting this limit directly in LibXray’s Go source code, before building it with gomobile - nothing changed. I never worked with golang before so I started reading about memory limits in its runtime. If I understood correctly, this code (from LibXray/nodep/memory.go):

```
 func InitForceFree(maxMemory int64, interval int) {
	debug.SetGCPercent(10)
	debug.SetMemoryLimit(maxMemory)
	if interval > 0 {
		duration := time.Duration(interval) * time.Second
		forceFree(duration)
	}
}
```

is not setting a “hard” memory limit, it’s just making GC to run more frequently, which cannot guarantee an actual memory limit compliance. That’s why even when I set this “soft” limit to an extremely low value of 2Mb, this did not fix the memory issue, nor broke the tunnel. LibXray was not able to fit into this limit, and probably went way beyond it. 

**Current PacketTunnelProvider code:**

```
private func startXray(path: String) throws {
        // Create RunXrayRequest
        let request = RunXrayRequest(datDir: Constant.assetDirectory.path, configPath: path, maxMemory:  16 * 1024 * 1024) 

        do {
            let jsonData = try JSONEncoder().encode(request)

            let base64String = jsonData.base64EncodedString()

            LibXrayRunXray(base64String)
        } catch {
            NSLog("Failed to encode RunXrayRequest: \(error.localizedDescription)")
            throw error
        }
    }

private func startSocks5Tunnel(serverPort port: Int = 10808) throws {
        let sockAddress: String
        if #available(iOS 17, *) {
            sockAddress = "::1"  // Use localhost for iOS 17+
        } else {
            sockAddress = "::1"    // Use all interfaces for iOS 15 and 16
        }
        
        let socks5Config = """
        tunnel:
          mtu: 8500

        socks5:
          port: \(port)
          address: \(sockAddress)
          udp: 'udp'

        misc:
          task-stack-size: 12800 # 12800 is the min for Speedtest not to fail
          # tcp buffer size (bytes)
          tcp-buffer-size: 4096 # 4096 is the min for Speedtest not to fail
          connect-timeout: 2000 # 2000 ms is the min for Speedtest not to fail
          read-write-timeout: 10000 # 10000 ms is the min for Speedtest not to fail
          log-file: stderr
          log-level: error.
          limit-nofile: 65535
        """
        Socks5Tunnel.run(withConfig: .string(content: socks5Config)) { code in
            if code == 0 {
                os_log("Tun2Socks started successfully")
            } else {
                os_log("Tun2Socks failed to start, error code: %{public}d", code)
            }
        }
    }

func setTunnelNetworkSettings() async throws {
        let settings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "fd00::1")
        settings.mtu = NSNumber(value: MTU)

        
        settings.ipv4Settings = {
            let ipv4 = NEIPv4Settings(
                addresses: ["198.18.0.1"],
                subnetMasks: ["255.255.255.0"]
            )

            let defaultV4Route = NEIPv4Route(
                destinationAddress: "0.0.0.0",
                subnetMask: "0.0.0.0"
            )
            defaultV4Route.gatewayAddress = "198.18.0.1"

            ipv4.includedRoutes = [defaultV4Route]
            ipv4.excludedRoutes = []
            return ipv4
        }()

        
        settings.ipv6Settings = {
            let ipv6 = NEIPv6Settings(
                addresses: ["fd6e:a81b:704f:1211::1"],
                networkPrefixLengths: [64]
            )

            let defaultV6Route = NEIPv6Route(
                destinationAddress: "::",
                networkPrefixLength: 0
            )
            defaultV6Route.gatewayAddress = "fd6e:a81b:704f:1211::1"

            ipv6.includedRoutes = [defaultV6Route]
            ipv6.excludedRoutes = []
            return ipv6
        }()

        // Set DNS servers
        settings.dnsSettings = NEDNSSettings(servers: ["1.1.1.1", "8.8.8.8", "8.8.4.4"/*, "114.114.114.114", "223.5.5.5"*/])

        // Apply settings to the tunnel
        try await setTunnelNetworkSettings(settings)
    }

override func startTunnel(options: [String: NSObject]? = nil) async throws {
        
        guard let sock5Port = options?["sock5Port"] as? Int else {
            return
        }

        guard let path = options?["path"] as? String else {
            return
        }

        do {
            try startXray(path: path)

            try await setTunnelNetworkSettings()

            try startSocks5Tunnel(serverPort: sock5Port)
        } catch {
            os_log("Error occurred while starting the service: %{public}@", error.localizedDescription)
            throw error
        }
    }
```

**Library versions:**
_Tun2SocksKit:_ tested on 4.8.0 and 4.9.1, the issue is consistent.
_LibXray:_ 25.1.30, 24.12.18, 25.2.21, the issue is consistent.

**The question is:** 
What should I do next? There are apps in the App Store that use xray-core, such as _FoXray_ and _Streisand_, they work just fine with the same servers that I tried in my app. So the problem can be solved. They probably make some custom build of Xray-core to remove everything the do not need to make a memory footprint lower or use some custom tun2socks code, I don’t actually know. 
From xray-core I need only vless with xtls-reality, how do I get rid of everything else? 
How can I investigate the current app further? May high memory consumption originate from Tun2SocksKit, not LibXray? 
Any advice will be appreciated.
